---
kind: pipeline
name: linux-amd64-docker
type: docker

steps:
  - name: publish
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      daemon_off: false
      dockerfile: Dockerfile
      auto_tag: true
      password:
        from_secret: DOCKER_PASS
      repo: remco1271/docker-apache-php
      username:
        from_secret: docker_username
      platforms: 
      - linux/arm64
      - linux/amd64
      - linux/arm/v7
trigger:
  event:
  - push
  - cron
  - custom