#!/bin/bash

# git pull latest iPXE repository
cd /var/tmp/ipxe && git pull
chown -R www-data:www-data /var/run/ipxe-build/ipxe-build-cache.lock /var/cache/ipxe-build /var/run/ipxe-build /var/tmp/ipxe-build /var/tmp/ipxe

# git pull latest buildweb
cd /var/www/ipxe-buildweb && git pull
cp parseheaders.pl /var/tmp/ipxe/src/util/

exec /usr/sbin/apache2 -D FOREGROUND
